DROP SCHEMA PUBLIC CASCADE

CREATE TABLE Inzeraty(
id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
portal varchar(255),
nazov varchar(255),
text varchar(4000),
meno varchar(255),
telefon varchar(255),
lokalita varchar(255),
aktualny_link varchar(255),
cena cena varchar(25),
time_inserted timestamp,
pocet_zobrazeni integer,
sent boolean,
zaujimavy boolean,
surne boolean,
precitany boolean,
typ varchar(20),
kategoria varchar(25)
);

CREATE TABLE remote_inzeraty(
id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
portal varchar(255),
nazov varchar(255),
text varchar(4000),
meno varchar(255),
telefon varchar(255),
lokalita varchar(255),
aktualny_link varchar(255),
cena cena varchar(25),
time_inserted timestamp,
pocet_zobrazeni integer,
sent boolean,
zaujimavy boolean,
surne boolean,
precitany boolean,
typ varchar(20),
kategoria varchar(25)
);

CREATE TABLE vybrane_mesta(
nazov varchar(25) UNIQUE,
);

CREATE TABLE najdene(
den int,
rok int,
portal varchar(25),
pocet int
);

CREATE TABLE aktualnosti(
portal varchar(255) UNIQUE,
datum timestamp
);

CREATE TABLE okresy(
obec varchar(255) UNIQUE,
okres varchar(255)
);

CREATE TABLE firemne_linky(
link varchar(255),
);

MYSQL:
CREATE TABLE Inzeraty( 
id INT NOT NULL, 
portal varchar(255),
nazov varchar(255),
text varchar(4000),
meno varchar(255),
telefon varchar(255),
lokalita varchar(255),
aktualny_link varchar(255),
cena varchar(25),
time_inserted timestamp,
pocet_zobrazeni integer,
sent boolean,
zaujimavy boolean,
surne boolean,
precitany boolean,
typ varchar(25),
kategoria varchar(25),
PRIMARY KEY ( id ) );

CREATE TABLE archiv(
id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
portal varchar(255),
nazov varchar(255),
text varchar(4000),
meno varchar(255),
telefon varchar(255),
lokalita varchar(255),
aktualny_link varchar(255),
cena varchar(25),
time_inserted timestamp,
archivacia_time timestamp,
pocet_zobrazeni integer,
sent boolean,
zaujimavy boolean,
surne boolean,
precitany boolean,
preposlany boolean,
typ varchar(255),
kategoria varchar(255),
archivcesta varchar(255)
);


create table nastavenia(
sprievodny_text varchar(1000)
)

alter table Inzeraty change last_modified time_inserted timestamp;
select * from Inzeraty where id=1;
alter table Inzeraty add typ varchar(20) default 'Ostatné';
select * from Inzeraty limit 10;



- time inserted
- pocet zobrazeni
- ci je nezaujimavy

alter table inzeraty alter column last_modified rename to time_inserted
alter table inzeraty add pocet_zobrazeni integer default '0' 
alter table inzeraty add preposlany boolean default false 

select id from inzeraty 
where id in (select id from inzeraty where 
month(time_inserted)=month(CURRENT_TIMESTAMP) 
and day(time_inserted)=day(CURRENT_TIMESTAMP)
and year(time_inserted)=year(CURRENT_TIMESTAMP))
and (text like '%súrne%' 
or text like '%surne%' 
or text like '%Surne%' 
or text like '%Súrne%' 
or text like '%SURNE%' 
or text like '%SÚRNE%' )
